### ISSUE TITLE
OpenMVG related code in this repo

### ISSUE THREAD

**Issue by pmoulon** [AIBluefisher/GraphOptim#4]
Thank you for releasing the code related to your paper.

I noticed that there are multiple files that are coming from OpenMVG code repository.

| Topic | This Repo | OpenMVG |
|-|-|-|
| SVG | https://github.com/AIBluefisher/GraphOptim/blob/main/src/graph/svg_drawer.h | https://github.com/openMVG/openMVG/blob/develop/src/third_party/vectorGraphics/svgDrawer.hpp |
|triplet| https://github.com/AIBluefisher/GraphOptim/blob/main/src/graph/triplet_extractor.h| https://github.com/openMVG/openMVG/blob/develop/src/openMVG/graph/triplet_finder.hpp |
|ColorGradient|https://github.com/AIBluefisher/GraphOptim/blob/main/src/graph/color_gradient.h|https://github.com/openMVG/openMVG/blob/develop/src/openMVG/graphics/color_gradient.hpp|
|l1 solver|https://github.com/AIBluefisher/GraphOptim/blob/main/src/solver/l1_solver.h|https://github.com/openMVG/openMVG/blob/develop/src/openMVG/numeric/l1_solver_admm.hpp|
...

There are also other files that have the same issue
https://github.com/AIBluefisher/GraphOptim/blob/main/src/util/alignment.h ...

There is also code from other repositories like THeiaSfM here https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/global_pose_estimation/least_unsquared_deviation_position_estimator.h
https://github.com/AIBluefisher/GraphOptim/blob/main/src/translation_averaging/lud_position_estimator.h

Please keep the initial copyright notice and respect the work that has been done by the open-source community before you.
Changing the name of the file is not enough to claim ownership of it.

I appreciate that you see the direct value of OpenMVG code and are leveraging it for other work, but the opensource community can thrive better if we support each other, and keep initial copyrights and licenses in the file we are reusing.

cc @laurentkneip

**Comment by AIBluefisher** [comment]
Thanks for your advice. The licenses are omitted at the first commit, and I have updated the code with license declarations.
