### ISSUE TITLE
rotation_estimator  std::bad_alloc

### ISSUE THREAD

**Issue by coder12333444** [AIBluefisher/GraphOptim#5]
@AIBluefisher 
HI,when I run the rotation_estimator ,the error like this:
`
./build/bin/rotation_estimator --g2o_filename=./data/synthetic/20_2.g2o
I0120 19:03:26.052269 18845 hybrid_rotation_estimator.cc:94] Estimating Rotations Using LagrangeDual
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
`
also when I run the ./lagrange_dual_rotation_estimator_test
`dual_rotation_estimator_test 
Running main() from gtest_main.cc
[==========] Running 15 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 15 tests from LagrangeDualRotationAveragingTest
[ RUN      ] LagrangeDualRotationAveragingTest.smallTestNoNoise
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0120 19:07:51.680837 19045 lagrange_dual_rotation_estimator_test.cc:88] 
Estimating Global Orientations using Lagrange Dual...
free(): invalid pointer
Aborted (core dumped)
`

**Comment by AIBluefisher** [comment]
I have no such problem with the app running on my PC. I wonder if you used the recommended version for all dependencies. Because my program once crashed when I use Eigen 3.3 or above.
